In [1]:
# Import the necessary libraries
#--------------------------------
import pandas as pd
import geopandas as gpd
import numpy as np
import math

In [2]:
# Load input data (ie ward boundaries and building footprints)
#--------------------------------------------------------------
gdf_boundaries = gpd.read_file(r"Churu_Ward_Boundaries_MHT.geojson")
buildings_gdf = gpd.read_parquet(r"Churu_buildings_with_OSM.parquet")

In [3]:
buildings_gdf

,perimeter_in_meters,building_faces,bf_source,confidence_left,geometry,longitude,latitude,id,area_in_meters,height_mean,...,First_AID_FA_vehicle,FA_vehicle_distance_km,FA_vehicle_time_min,District_Hospital_DH_pedestrian,DH_pedestrian_distance_km,DH_pedestrian_time_min,First_AID_FA_pedestrian,FA_pedestrian_distance_km,FA_pedestrian_time_min,imputed_from
0,7.243843,4,google,0.7724,"POLYGON ((74.23236 27.72641, 74.23236 27.72641...",74.232350,27.726409,74.23234975129046:27.72640873664523,0.000125,0.000000,...,Luhara - phc,0.07,0.2,District hospital Nagaur - dis_h,88.69,1064.3,Luhara - phc,0.07,0.8,None
1,9.011801,4,google,0.7108,"POLYGON ((74.84492 28.873, 74.84492 28.87303, ...",74.844915,28.873013,74.84491545220574:28.873013019801967,0.000126,1.000000,...,Sahawa - chc,0.19,0.5,D B Government Hospital Churu - dis_h,87.27,1047.2,Sahawa - chc,0.19,2.3,None
2,6.354292,4,google,0.7123,"POLYGON ((74.22657 27.63066, 74.22656 27.63067...",74.226555,27.630664,74.22655544425939:27.630663527650903,0.000126,1.722222,...,Khara - sub_cen,4.21,10.1,District hospital Nagaur - dis_h,80.56,966.7,Parawa - sub_cen,2.90,34.8,None
3,6.957619,4,google,0.7604,"POLYGON ((75.01403 28.33486, 75.01403 28.33487...",75.014020,28.334861,75.0140202674914:28.334861398658834,0.000126,0.000000,...,Boontia - sub_cen,1.85,4.6,D B Government Hospital Churu - dis_h,8.53,102.4,Boontia - sub_cen,1.85,22.2,None
4,8.217702,4,google,0.7845,"POLYGON ((74.5701 27.78267, 74.5701 27.7827, 7...",74.570094,27.782683,74.57009354210085:27.782682537523247,0.000127,2.500000,...,Badawar - phc,0.31,0.5,"S K Hospital, Sikar - dis_h",69.99,839.8,Badawar - phc,0.31,3.8,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481129,288.063775,4,google,0.9623,"POLYGON ((74.47232 28.41938, 74.4719 28.42, 74...",74.471835,28.419541,74.47183471063026:28.41954127037166,0.255824,10.031507,...,Sardarsahar - chc,3.43,5.0,D B Government Hospital Churu - dis_h,66.48,797.7,Sardarsahar - chc,3.43,41.2,None
1481130,309.362995,6,google,0.8996,"POLYGON ((74.96017 28.19513, 74.9602 28.19508,...",74.960137,28.195540,74.96013678708111:28.195540360926653,0.275961,6.671840,...,Ratannagar - chc,2.31,2.5,D B Government Hospital Churu - dis_h,12.93,155.2,Ratannagar - chc,1.83,22.0,None
1481131,444.405058,21,google,0.9111,"POLYGON ((75.37975 28.63027, 75.37973 28.6301,...",75.380226,28.630323,75.38022567723831:28.630323167273463,0.276669,8.208935,...,Rajgarh - chc,2.52,2.5,D B Government Hospital Churu - dis_h,67.89,814.7,Rajgarh - chc,2.17,26.1,None
1481132,382.805856,16,google,0.9185,"POLYGON ((75.3449 28.39026, 75.34491 28.39022,...",75.344910,28.390703,75.34491042205822:28.390703116146657,0.300631,7.102821,...,Rawatsar Kujala - sub_cen,1.71,4.1,B.D.K. Hospital Jhunjhunun - dis_h,33.53,402.4,Rawatsar Kujala - sub_cen,1.71,20.6,None
1481133,426.436013,6,google,0.9578,"POLYGON ((74.95986 28.19321, 74.95965 28.19361...",74.959098,28.193233,74.95909777279351:28.193232751039115,0.456780,10.471561,...,Ratannagar - chc,2.50,2.6,D B Government Hospital Churu - dis_h,12.93,155.2,Ratannagar - chc,1.83,22.0,None

In [4]:
gdf_boundaries

,OBJECTID,Name,bvnvb,Shape_Leng,Shape_Area,Ward_sqkm,Percentage,Per_inter,geometry
0,1.0,34,34.0,2994.929840,2.419409e+05,0.242,23.967,NaN,"MULTIPOLYGON (((497413.347 3129795.635, 497432..."
1,2.0,1,1.0,8789.786444,2.305656e+06,2.307,4.725,8.626,"MULTIPOLYGON (((492617.58 3130342.225, 492616...."
2,3.0,4,4.0,7979.093807,1.740005e+06,1.741,9.765,3.044,"MULTIPOLYGON (((494540.406 3129533.656, 494538..."
3,4.0,2,2.0,3002.349186,2.590953e+05,0.259,NaN,NaN,"MULTIPOLYGON (((495502.887 3131172.422, 495503..."
4,5.0,5,5.0,1356.361713,7.908319e+04,0.079,NaN,NaN,"MULTIPOLYGON (((495745.314 3130828.325, 495752..."
5,6.0,3,3.0,2044.537291,1.642186e+05,0.164,NaN,NaN,"MULTIPOLYGON (((495890.081 3130893.476, 495867..."
6,7.0,8,8.0,1003.513210,4.125380e+04,0.041,NaN,48.780,"MULTIPOLYGON (((496040.554 3130563.262, 496017..."
7,8.0,6,6.0,1473.824366,9.274238e+04,0.093,NaN,NaN,"MULTIPOLYGON (((496163.12 3130732.687, 496165...."
8,9.0,58,58.0,1678.334455,1.226817e+05,0.123,NaN,NaN,"MULTIPOLYGON (((496270.673 3131181.759, 496243..."
9,10.0,60,60.0,3696.772565,2.942562e+05,0.294,NaN,NaN,"MULTIPOLYGON (((496025.865 3131334.261, 496022..."
10,11.0,59,59.0,4241.668435,1.000343e+06,1.001,NaN,0.400,"MULTIPOLYGON (((496558.419 3131493.285, 496502..."
11,12.0,54,54.0,4036.572654,4.500521e+05,0.450,NaN,40.889,"MULTIPOLYGON (((496817.532 3132182.472, 496846..."
12,13.0,56,56.0,1947.458387,1.090697e+05,0.109,NaN,7.339,"MULTIPOLYGON (((496607.223 3131958.667, 496623..."
13,14.0,53,53.0,1302.399977,7.740423e+04,0.077,NaN,33.766,"MULTIPOLYGON (((497012.259 3131743.28, 496968...."
14,15.0,51,51.0,1511.571591,5.941558e+04,0.059,NaN,1.695,"MULTIPOLYGON (((497105.783 3131672.755, 497097..."
15,16.0,14,14.0,3838.339908,4.771270e+05,0.478,NaN,38.075,"MULTIPOLYGON (((494557.669 3129449.586, 494540..."
16,17.0,13,13.0,1786.176233,1.331046e+05,0.133,NaN,32.331,"MULTIPOLYGON (((495895.212 3130180.12, 495880...."
17,18.0,12,12.0,1189.813735,7.641364e+04,0.076,NaN,17.105,"MULTIPOLYGON (((495980.692 3130281.69, 495964...."
18,19.0,9,9.0,744.791039,2.880258e+04,0.029,NaN,100.000,"MULTIPOLYGON (((496214.628 3130457.467, 496195..."
19,20.0,11,11.0,780.932155,2.323160e+04,0.023,NaN,52.174,"MULTIPOLYGON (((496200.577 3130368.12, 496201...."
20,21.0,15,15.0,5442.678778,8.237487e+05,0.824,NaN,2.549,"MULTIPOLYGON (((496260.473 3130170.077, 496270..."
21,22.0,19,19.0,6600.281496,1.460257e+06,1.461,NaN,13.758,"MULTIPOLYGON (((494701.427 3127726.316, 494705..."
22,23.0,16,16.0,2681.681494,1.601009e+05,0.160,NaN,35.000,"MULTIPOLYGON (((496373.269 3129774.734, 496385..."
23,24.0,17,17.0,1810.881476,1.258111e+05,0.126,NaN,2.381,"MULTIPOLYGON (((496570.355 3129753.016, 496444..."
24,25.0,10,10.0,1470.395664,6.481162e+04,0.065,NaN,98.462,"MULTIPOLYGON (((496485.997 3130248.705, 496438..."
25,26.0,7,7.0,1588.685202,1.002485e+05,0.100,0.000,29.000,"MULTIPOLYGON (((496508.548 3130670.536, 496458..."
26,27.0,28,28.0,2113.018289,1.696249e+05,0.170,72.353,11.176,"MULTIPOLYGON (((496509.838 3130675.182, 496511..."
27,28.0,27,27.0,1114.780985,5.626948e+04,0.056,NaN,35.714,"MULTIPOLYGON (((496549.5 3130463.721, 496553.5..."
28,29.0,26,26.0,1758.046634,1.013258e+05,0.101,NaN,22.772,"MULTIPOLYGON (((496736.75 3129839.075, 496704...."
29,30.0,22,22.0,4106.173271,5.377348e+05,0.538,15.613,29.926,"MULTIPOLYGON (((496712.04 3129235.887, 496807...."
30,31.0,20,20.0,5161.192508,1.468587e+06,1.470,NaN,NaN,"MULTIPOLYGON (((496146.883 3128568.768, 496043..."
31,32.0,21,21.0,6949.820832,1.784787e+06,1.786,NaN,1.064,"MULTIPOLYGON (((497199.682 3128479.577, 497197..."
32,33.0,31,31.0,6810.757688,1.525111e+06,1.526,1.769,6.422,"MULTIPOLYGON (((498229.007 3128509.813, 498229..."
33,34.0,32,32.0,7268.363825,2.372506e+06,2.374,NaN,NaN,"MULTIPOLYGON (((500163.598 3129454.633, 499999..."
34,35.0,33,33.0,7814.840933,2.054584e+06,2.056,NaN,NaN,"MULTIPOLYGON (((498127.116 3129592.631, 498101..."
35,36.0,38,38.0,4673.698782,4.324994e+05,0.433,NaN,NaN,"MULTIPOLYGON (((497625.748 3130238.169, 497619..."
36,37.0,29,29.0,2823.094902,2.946724e+05,0.295,3.051,15.593,"MULTIPOLYGON (((496897.576 3129871.816, 496895..."
37,38.0,55,55.0,2252.979320,1.973408e+05,0.197,27.411,18.782,"MULTIPOLYGON (((496879.197 3131734.772, 496916..."
38,39.0,48,48.0,1739.187841,8.850752e+04,0.089,NaN,21.348,"MULTIPOLYGON (((497514.73 3131798.354, 497515...."
39,40.0,52,52.0,1396.964367,7.500621e+04,0.075,NaN,1.333,"MULTIPOLYGON (((497311.644 3131568.376, 497204..."
40,41.0,50,50.0,3760.820207,4.635029e+05,0.464,NaN,42.241,"MULTIPOLYGON (((498238.298 3132045.541, 497855..."
41,42.0,49,49.0,2343.472602,1.886835e+05,0.189,NaN,3.704,"MULTIPOLYGON (((498380.792 3131873.348, 498081..."
42,43.0,47,47.0,3027.168581,2.010054e+05,0.201,NaN,0.995,"MULTIPOLYGON (((498513.463 3131713.024, 498496..."
43,44.0,43,43.0,2032.245612,1.833362e+05,0.183,NaN,18.033,"MULTIPOLYGON (((497418.605 3131248.494, 497450..."
44,45.0,46,46.0,3476.519043,5.477995e+05,0.548,NaN,44.161,"MULTIPOLYGON (((498883.694 3131265.629, 498558..."
45,46.0,45,45.0,1955.307234,1.182345e+05,0.118,NaN,43.220,"MULTIPOLYGON (((497293.877 3130999.023, 497286..."
46,47.0,42,42.0,4239.710132,6.170509e+05,0.618,NaN,0.162,"MULTIPOLYGON (((497514.294 3130682.915, 497519..."
47,48.0,44,44.0,1908.550620,9.065587e+04,0.091,8.791,87.912,"MULTIPOLYGON (((497309.594 3130931.236, 497310..."
48,49.0,41,41.0,2324.404399,1.415384e+05,0.142,4.225,33.803,"MULTIPOLYGON (((497417.793 3130668.052, 497395..."
49,50.0,40,40.0,1242.873825,5.177174e+04,0.052,NaN,NaN,"MULTIPOLYGON (((497428.289 3130582.444, 497429..."
50,51.0,39,39.0,1341.680656,5.767049e+04,0.058,NaN,NaN,"MULTIPOLYGON (((497516.184 3130314.495, 497481..."
51,52.0,37,37.0,956.714371,4.105303e+04,0.041,NaN,NaN,"MULTIPOLYGON (((497767.188 3130128.354, 497748..."
52,53.0,36,36.0,1867.160359,1.070216e+05,0.107,0.935,NaN,"MULTIPOLYGON (((497563.516 3130055.351, 497533..."
53,54.0,35,35.0,1459.582438,1.000880e+05,0.100,NaN,NaN,"MULTIPOLYGON (((497840.262 3129920.376, 497790..."
54,55.0,24,24.0,1236.779625,5.691168e+04,0.057,61.404,NaN,"MULTIPOLYGON (((496704.638 3129834.092, 496736..."
55,56.0,23,23.0,1595.364168,1.179075e+05,0.118,4.237,NaN,"MULTIPOLYGON (((496956.355 3129431.285, 496951..."
56,57.0,30,30.0,1746.940822,1.239219e+05,0.124,56.452,NaN,"MULTIPOLYGON (((496798.927 3129853.958, 496861..."
57,58.0,25,25.0,973.482126,3.578634e+04,0.036,NaN,NaN,"MULTIPOLYGON (((496897.576 3129871.816, 496863..."
58,59.0,57,57.0,1793.631151,1.331904e+05,0.133,58.647,9.774,"MULTIPOLYGON (((496955.906 3131021.644, 496944..."
59,60.0,16,18.0,1924.912843,1.600564e+05,0.160,NaN,35.000,"MULTIPOLYGON (((496348.656 3129550.521, 496362..."

In [5]:
# Filter residential buildings 
#------------------------------
churu_res_buildings = buildings_gdf[buildings_gdf["prediction"] == "Residential"]
churu_other_buildings = buildings_gdf[buildings_gdf["prediction"] != "Residential"]
churu_res_buildings["geometry2"] = buildings_gdf["geometry"]

/usr/local/lib/python3.12/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [6]:
# Recreate geometrires from lat/lon (convert to point geometries)
#----------------------------------------------------------------- 
churu_res_buildings = gpd.GeoDataFrame(
    churu_res_buildings,
    geometry=gpd.points_from_xy(churu_res_buildings["longitude"], churu_res_buildings["latitude"]),
    crs="EPSG:4326"
)
churu_res_buildings

,perimeter_in_meters,building_faces,bf_source,confidence_left,geometry,longitude,latitude,id,area_in_meters,height_mean,...,FA_vehicle_distance_km,FA_vehicle_time_min,District_Hospital_DH_pedestrian,DH_pedestrian_distance_km,DH_pedestrian_time_min,First_AID_FA_pedestrian,FA_pedestrian_distance_km,FA_pedestrian_time_min,imputed_from,geometry2
0,7.243843,4,google,0.7724,POINT (74.23235 27.72641),74.232350,27.726409,74.23234975129046:27.72640873664523,0.000125,0.000000,...,0.07,0.2,District hospital Nagaur - dis_h,88.69,1064.3,Luhara - phc,0.07,0.8,None,"POLYGON ((74.23236 27.72641, 74.23236 27.72641..."
1,9.011801,4,google,0.7108,POINT (74.84492 28.87301),74.844915,28.873013,74.84491545220574:28.873013019801967,0.000126,1.000000,...,0.19,0.5,D B Government Hospital Churu - dis_h,87.27,1047.2,Sahawa - chc,0.19,2.3,None,"POLYGON ((74.84492 28.873, 74.84492 28.87303, ..."
2,6.354292,4,google,0.7123,POINT (74.22656 27.63066),74.226555,27.630664,74.22655544425939:27.630663527650903,0.000126,1.722222,...,4.21,10.1,District hospital Nagaur - dis_h,80.56,966.7,Parawa - sub_cen,2.90,34.8,None,"POLYGON ((74.22657 27.63066, 74.22656 27.63067..."
3,6.957619,4,google,0.7604,POINT (75.01402 28.33486),75.014020,28.334861,75.0140202674914:28.334861398658834,0.000126,0.000000,...,1.85,4.6,D B Government Hospital Churu - dis_h,8.53,102.4,Boontia - sub_cen,1.85,22.2,None,"POLYGON ((75.01403 28.33486, 75.01403 28.33487..."
4,8.217702,4,google,0.7845,POINT (74.57009 27.78268),74.570094,27.782683,74.57009354210085:27.782682537523247,0.000127,2.500000,...,0.31,0.5,"S K Hospital, Sikar - dis_h",69.99,839.8,Badawar - phc,0.31,3.8,None,"POLYGON ((74.5701 27.78267, 74.5701 27.7827, 7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481070,288.940417,4,google,0.9654,POINT (75.49377 28.83493),75.493774,28.834925,75.49377437705633:28.83492532996736,0.124482,5.496721,...,0.51,0.8,Maharaja Aggarsain Medical College AGROHA - dis_h,53.42,641.0,Nyangal Chhoti - sub_cen,0.51,6.2,None,"POLYGON ((75.49442 28.83487, 75.4944 28.83505,..."
1481075,413.929305,16,microsoft,NaN,POINT (75.48835 28.57079),75.488354,28.570791,75.48835436178372:28.570790796491007,0.128104,0.000000,...,0.87,1.3,B.D.K. Hospital Jhunjhunun - dis_h,74.42,893.1,Kalari - phc,0.87,10.4,None,"POLYGON ((75.48861 28.5707, 75.48865 28.57068,..."
1481083,289.408869,24,google,0.9092,POINT (74.9331 28.20512),74.933096,28.205125,74.93309554461749:28.205124977994227,0.135970,8.185522,...,2.39,3.8,D B Government Hospital Churu - dis_h,13.48,161.8,Ratannagar - chc,2.39,28.6,None,"POLYGON ((74.93284 28.20498, 74.93285 28.20498..."
1481106,351.817061,31,microsoft,NaN,POINT (75.49022 28.56949),75.490217,28.569488,75.49021717721772:28.56948776087451,0.158354,0.000000,...,0.70,1.1,B.D.K. Hospital Jhunjhunun - dis_h,74.26,891.1,Kalari - phc,0.70,8.4,None,"POLYGON ((75.48981 28.56982, 75.48979 28.56983..."
1481115,411.959447,4,google,0.9413,POINT (75.49338 28.83599),75.493376,28.835985,75.49337609877716:28.835985281020527,0.181060,6.478261,...,0.61,0.9,Maharaja Aggarsain Medical College AGROHA - dis_h,53.32,639.9,Nyangal Chhoti - sub_cen,0.61,7.3,None,"POLYGON ((75.49434 28.83594, 75.49433 28.83612..."

In [7]:
# Match CRS
#------------
churu_res_buildings = churu_res_buildings.to_crs(gdf_boundaries.crs)
churu_res_buildings

,perimeter_in_meters,building_faces,bf_source,confidence_left,geometry,longitude,latitude,id,area_in_meters,height_mean,...,FA_vehicle_distance_km,FA_vehicle_time_min,District_Hospital_DH_pedestrian,DH_pedestrian_distance_km,DH_pedestrian_time_min,First_AID_FA_pedestrian,FA_pedestrian_distance_km,FA_pedestrian_time_min,imputed_from,geometry2
0,7.243843,4,google,0.7724,POINT (424331.627 3067131.713),74.232350,27.726409,74.23234975129046:27.72640873664523,0.000125,0.000000,...,0.07,0.2,District hospital Nagaur - dis_h,88.69,1064.3,Luhara - phc,0.07,0.8,None,"POLYGON ((74.23236 27.72641, 74.23236 27.72641..."
1,9.011801,4,google,0.7108,POINT (484876.34 3193926.563),74.844915,28.873013,74.84491545220574:28.873013019801967,0.000126,1.000000,...,0.19,0.5,D B Government Hospital Churu - dis_h,87.27,1047.2,Sahawa - chc,0.19,2.3,None,"POLYGON ((74.84492 28.873, 74.84492 28.87303, ..."
2,6.354292,4,google,0.7123,POINT (423693.943 3056529.04),74.226555,27.630664,74.22655544425939:27.630663527650903,0.000126,1.722222,...,4.21,10.1,District hospital Nagaur - dis_h,80.56,966.7,Parawa - sub_cen,2.90,34.8,None,"POLYGON ((74.22657 27.63066, 74.22656 27.63067..."
3,6.957619,4,google,0.7604,POINT (501374.223 3134297.669),75.014020,28.334861,75.0140202674914:28.334861398658834,0.000126,0.000000,...,1.85,4.6,D B Government Hospital Churu - dis_h,8.53,102.4,Boontia - sub_cen,1.85,22.2,None,"POLYGON ((75.01403 28.33486, 75.01403 28.33487..."
4,8.217702,4,google,0.7845,POINT (457645.79 3073203.448),74.570094,27.782683,74.57009354210085:27.782682537523247,0.000127,2.500000,...,0.31,0.5,"S K Hospital, Sikar - dis_h",69.99,839.8,Badawar - phc,0.31,3.8,None,"POLYGON ((74.5701 27.78267, 74.5701 27.7827, 7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481070,288.940417,4,google,0.9654,POINT (548170.125 3189797.089),75.493774,28.834925,75.49377437705633:28.83492532996736,0.124482,5.496721,...,0.51,0.8,Maharaja Aggarsain Medical College AGROHA - dis_h,53.42,641.0,Nyangal Chhoti - sub_cen,0.51,6.2,None,"POLYGON ((75.49442 28.83487, 75.4944 28.83505,..."
1481075,413.929305,16,microsoft,NaN,POINT (547761.161 3160531.774),75.488354,28.570791,75.48835436178372:28.570790796491007,0.128104,0.000000,...,0.87,1.3,B.D.K. Hospital Jhunjhunun - dis_h,74.42,893.1,Kalari - phc,0.87,10.4,None,"POLYGON ((75.48861 28.5707, 75.48865 28.57068,..."
1481083,289.408869,24,google,0.9092,POINT (493434.283 3119927.267),74.933096,28.205125,74.93309554461749:28.205124977994227,0.135970,8.185522,...,2.39,3.8,D B Government Hospital Churu - dis_h,13.48,161.8,Ratannagar - chc,2.39,28.6,None,"POLYGON ((74.93284 28.20498, 74.93285 28.20498..."
1481106,351.817061,31,microsoft,NaN,POINT (547943.937 3160388.159),75.490217,28.569488,75.49021717721772:28.56948776087451,0.158354,0.000000,...,0.70,1.1,B.D.K. Hospital Jhunjhunun - dis_h,74.26,891.1,Kalari - phc,0.70,8.4,None,"POLYGON ((75.48981 28.56982, 75.48979 28.56983..."
1481115,411.959447,4,google,0.9413,POINT (548130.783 3189914.361),75.493376,28.835985,75.49337609877716:28.835985281020527,0.181060,6.478261,...,0.61,0.9,Maharaja Aggarsain Medical College AGROHA - dis_h,53.32,639.9,Nyangal Chhoti - sub_cen,0.61,7.3,None,"POLYGON ((75.49434 28.83594, 75.49433 28.83612..."

In [8]:
# Uses spatial join to assign each res building the ward name of the polygon it falls within.
# Buildings that don't fall inside any ward polygon are removed
#--------------------------------------------------------------------------------------------
joined = gpd.sjoin(churu_res_buildings, gdf_boundaries, how="left", predicate="within")
joined_wo_nan = joined[joined['Name'].notna()]
churu_res_buildings = joined_wo_nan

In [9]:
churu_res_buildings.columns

Index(['perimeter_in_meters', 'building_faces', 'bf_source', 'confidence_left',
       'geometry', 'longitude', 'latitude', 'id', 'area_in_meters',
       'height_mean', 'height_median', 'height_max', 'height', 'floors',
       'gfa_in_meters', 'urban_split', 'ghsl_smod', 'elevation',
       'building_density_50', 'building_density_100', 'building_density_250',
       'building_density_500', 'building_perimeter_in_meters_new',
       'perimeter_to_area_ratio', 'normalized_perimeter_to_area_ratio',
       'centroid', 'radius_m', 'num_vertices', 'classification_source',
       'osm_type', 'centroid_x', 'centroid_y', 'nearest_road_type_1',
       'distance_to_1', 'nearest_road_type_2', 'distance_to_2',
       'nearest_road_type_3', 'distance_to_3', 'nearest_road_type_4',
       'distance_to_4', 'road_density_for_4_fixed', 'road_density_for_5_fixed',
       'SQN', 'faces', 'prediction', 'confidence_settlement_clasification',
       'settlement_clasification', 'Tree_Cover_TC_air_distance_km',
       'TC_area_Ha', 'Water_Seasonality_air_distance_km',
       'Water_Seasonality_area_Ha', 'District_Hospita_DH_vehicle',
       'DH_vehicle_distance_km', 'DH_vehicle_time_min', 'First_AID_FA_vehicle',
       'FA_vehicle_distance_km', 'FA_vehicle_time_min',
       'District_Hospital_DH_pedestrian', 'DH_pedestrian_distance_km',
       'DH_pedestrian_time_min', 'First_AID_FA_pedestrian',
       'FA_pedestrian_distance_km', 'FA_pedestrian_time_min', 'imputed_from',
       'geometry2', 'index_right', 'OBJECTID', 'Name', 'bvnvb', 'Shape_Leng',
       'Shape_Area', 'Ward_sqkm', 'Percentage', 'Per_inter'],
      dtype='object')

In [10]:
#file from MHT
#!pip install openpyxl
import openpyxl

population_churu = pd.read_excel(r"Churu Population.xlsx")
population_churu

,Ward Number,Total Population,Female,Male,Illiterate Population,Shape_Area (sq m),Area (sq_km),Density,Pop_2025
0,1,1873,899.04,973.96,505.71,2.305656e+06,2.305656,812.350066,2687.755
1,2,1830,878.40,951.60,494.10,2.590953e+05,0.259095,7063.038622,2626.050
2,3,1952,936.96,1015.04,527.04,1.642186e+05,0.164219,11886.591651,2801.120
3,4,1816,871.68,944.32,490.32,1.740005e+06,1.740005,1043.675241,2605.960
4,5,1852,888.96,963.04,500.04,7.908319e+04,0.079083,23418.376475,2657.620
...,...,...,...,...,...,...,...,...,...
56,57,2233,1071.84,1161.16,602.91,1.331904e+05,0.133190,16765.466442,3204.355
57,58,2334,1120.32,1213.68,630.18,1.226817e+05,0.122682,19024.842586,3349.290
58,59,1881,902.88,978.12,507.87,1.000343e+06,1.000343,1880.355270,2699.235
59,60,2042,980.16,1061.84,551.34,2.942562e+05,0.294256,6939.530709,2930.270
60,Total,119846,57526.08,62319.92,32358.42,2.520662e+07,25.206616,NaN,171979.010

In [11]:
# Compute total ground floor area
#---------------------------------
total_gfa = churu_res_buildings['gfa_in_meters'].sum()
total_gfa

np.float64(3121252.2948100003)

In [12]:
#average gfa per inhabitant 
total_population = 171979.010
average_area_per_inhabitant = total_gfa / total_population
average_area_per_inhabitant

np.float64(18.14903048232456)

In [13]:
# Estimate inhabitants per res building for Churu and adds new column (inhabitants_whole_churu)
#-----------------------------------------------------------------------------------------------
churu_res_buildings["inhabitants_whole_churu"] = (churu_res_buildings["gfa_in_meters"] / total_gfa) * total_population
churu_res_buildings['Name'].astype(int)
churu_res_buildings['Name'].astype(str)

/usr/local/lib/python3.12/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

43         47
69          1
112        10
147        17
160        51
           ..
1480608    16
1480617    23
1480660     1
1480666    19
1480732    29
Name: Name, Length: 33577, dtype: object

In [15]:
# without decimal numbers
# This cell creates a whole number estimate of people per res building for each ward, while ensuring the sum per ward equals the value in Pop_2025 in the excel file
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------

churu_res_buildings = churu_res_buildings.copy()
churu_res_buildings["inhabitants_with_integer_estimate"] = np.nan

# loop through each ward and filter res buildings that belong to that ward
for ward in range(1, 61):
    try:
        mask = churu_res_buildings["Name"].astype(int) == ward
    except:
        mask = churu_res_buildings["Name"].astype(str) == str(ward)
    
    df_ward = churu_res_buildings.loc[mask].copy()

    # Get the ward's population data from excel and skip wards with missing data
    try:
        pop_row = population_churu[population_churu["Ward Number"].astype(int) == ward]
    except:
        pop_row = population_churu[population_churu["Ward Number"].astype(str) == str(ward)]
    
    if df_ward.empty or pop_row.empty:
        continue
    
    total_pop = int(round(pop_row["Pop_2025"].values[0]))
    total_gfa = df_ward["gfa_in_meters"].sum() # total gfa per ward
    if total_gfa == 0:
        continue

    df_ward["ROcc"] = (df_ward["gfa_in_meters"] / total_gfa) * total_pop # raw continous population estimate
    df_ward["IOcc"] = np.floor(df_ward["ROcc"]).astype(int) # takes the integer part (rounds down) of each ROcc value
    df_ward["FOcc"] = df_ward["ROcc"] - df_ward["IOcc"] # Fractional remainder

    # Compute the number of people that still need to be added and allocate based on the deserve factor
    deficit = int(round(total_pop - df_ward["IOcc"].sum()))
    if deficit <= 0:
        churu_res_buildings.loc[mask, "inhabitants_with_integer_estimate"] = df_ward["IOcc"].values
        continue

    df_ward["DeserveFactor"] = np.where(df_ward["IOcc"] > 0, df_ward["FOcc"] / df_ward["IOcc"], 1.0)

    top_idx = df_ward["DeserveFactor"].nlargest(deficit).index
    df_ward.loc[top_idx, "IOcc"] += 1

    churu_res_buildings.loc[mask, "inhabitants_with_integer_estimate"] = df_ward["IOcc"].values

In [16]:
churu_res_buildings['inhabitants_with_integer_estimate']

43           1.0
69           1.0
112          1.0
147          1.0
160          1.0
           ...
1480608     70.0
1480617    111.0
1480660     37.0
1480666     38.0
1480732     47.0
Name: inhabitants_with_integer_estimate, Length: 33577, dtype: float64

In [17]:
#without decimal numbers + informal settlements constant
# This cell generates a new column (inhabitants_with_integer_informal) that estimates per-building integer inhabitants, using the same logic as the prev cell, 
# but with an extra weight (informal_multiplier = 4) applied to buildings classified as informal.
#---------------------------------------------------------------------------------------------------------------------------------------------------------------
churu_res_buildings = churu_res_buildings.copy()
churu_res_buildings["inhabitants_with_integer_informal"] = np.nan

informal_multiplier = 4

for ward in range(1, 61):
    mask = churu_res_buildings["Name"].astype(str) == str(ward)
    df_ward = churu_res_buildings.loc[mask].copy()
    pop_row = population_churu[population_churu["Ward Number"] == ward]
    
    if df_ward.empty or pop_row.empty:
        continue
    
    total_pop = int(round(pop_row["Pop_2025"].values[0]))
    total_gfa = df_ward["gfa_in_meters"].sum()
    if total_gfa == 0:
        continue
    
    df_ward["weight"] = np.where(df_ward["settlement_clasification"].str.lower() == "informal", informal_multiplier, 1)
    df_ward["weighted_gfa"] = df_ward["gfa_in_meters"] * df_ward["weight"]
    total_weighted_gfa = df_ward["weighted_gfa"].sum()
    

    df_ward["ROcc"] = (df_ward["weighted_gfa"] / total_weighted_gfa) * total_pop
    

    df_ward["IOcc"] = np.floor(df_ward["ROcc"]).astype(int)
    df_ward["FOcc"] = df_ward["ROcc"] - df_ward["IOcc"]
    
    deficit = int(round(total_pop - df_ward["IOcc"].sum()))
    if deficit <= 0:
        churu_res_buildings.loc[mask, "inhabitants_with_integer_informal"] = df_ward["IOcc"].values
        continue

    df_ward["DeserveFactor"] = np.where(df_ward["IOcc"] > 0, df_ward["FOcc"] / df_ward["IOcc"], 1)
    
    top_idx = df_ward["DeserveFactor"].nlargest(deficit).index
    df_ward.loc[top_idx, "IOcc"] += 1
    

    churu_res_buildings.loc[mask, "inhabitants_with_integer_informal"] = df_ward["IOcc"].values

In [18]:
# Save only res buildings inside the wards with population estimates 
#--------------------------------------------------------------------
churu_res_buildings['geometry'] = churu_res_buildings['geometry2']
res_with_pop = churu_res_buildings.copy()
print(res_with_pop.geometry.total_bounds)


res_with_pop.set_crs("EPSG:4326", inplace=True, allow_override=True)

# # Save as Parquet
output_path = "churu_res_60_wards_with_population.parquet"
res_with_pop.to_parquet(output_path, index=False, engine="pyarrow")

print(res_with_pop.crs)
print(res_with_pop.geometry.geom_type.value_counts())

res_with_pop.head()

[74.92465697 28.26977178 75.00352777 28.3232721 ]
EPSG:4326
Polygon    33577
Name: count, dtype: int64

,perimeter_in_meters,building_faces,bf_source,confidence_left,geometry,longitude,latitude,id,area_in_meters,height_mean,...,Name,bvnvb,Shape_Leng,Shape_Area,Ward_sqkm,Percentage,Per_inter,inhabitants_whole_churu,inhabitants_with_integer_estimate,inhabitants_with_integer_informal
43,6.881646,4,google,0.7285,"POLYGON ((74.97421 28.30772, 74.97421 28.30774...",74.974198,28.307729,74.9741978462364:28.307729275278096,0.000136,2.166667,...,47,47.0,3027.168581,2.010054e+05,0.201,NaN,0.995,0.149795,1.0,1.0
69,7.007497,4,google,0.7928,"POLYGON ((74.9514 28.3073, 74.9514 28.30732, 7...",74.951391,28.307306,74.9513908477859:28.30730566614702,0.000141,0.000000,...,1,1.0,8789.786444,2.305656e+06,2.307,4.725,8.626,0.155496,1.0,1.0
112,6.909840,4,google,0.7027,"POLYGON ((74.96247 28.29955, 74.96247 28.29957...",74.962459,28.299556,74.96245903512192:28.2995564344419,0.000149,4.222222,...,10,10.0,1470.395664,6.481162e+04,0.065,NaN,98.462,0.163704,1.0,1.0
147,7.235648,4,google,0.7013,"POLYGON ((74.96398 28.29727, 74.96398 28.29729...",74.963972,28.297278,74.96397245063798:28.297277583031956,0.000154,6.900000,...,17,17.0,1810.881476,1.258111e+05,0.126,NaN,2.381,0.339073,1.0,1.0
160,7.054727,4,google,0.7199,"POLYGON ((74.97085 28.31411, 74.97084 28.31412...",74.970836,28.314113,74.97083611088743:28.314113464876772,0.000156,2.166667,...,51,51.0,1511.571591,5.941558e+04,0.059,NaN,1.695,0.171375,1.0,1.0

In [19]:
# #adding back geometry + nonres buildings
# churu_res_buildings['geometry'] = churu_res_buildings['geometry2'] 
# merged = pd.concat([churu_res_buildings, churu_other_buildings], ignore_index=True)

In [20]:
# merged_gdf = gpd.GeoDataFrame(merged, geometry='geometry')
# merged_gdf = merged_gdf.to_crs(epsg=4326)
# merged_gdf.to_parquet("churu_60_wards_with_population.parquet")

In [21]:
# merge and save the complete dataset including res buildings inside wards, other res buildings outside the ward boundaries, non-res buildings
#-----------------------------------------------------------------------------------------------------------------------------------------------

# Other residential buildings outside wards (those dropped earlier) 
churu_other_res = joined[joined["Name"].isna()].copy()
churu_other_res["geometry"] = churu_other_res["geometry2"] # restore polygons

# Ensure CRS is consistent
for gdf in [churu_res_buildings, churu_other_buildings, churu_other_res]:
    gdf.set_crs("EPSG:4326", inplace=True, allow_override=True)

# Merge all subsets 
merged = pd.concat([churu_res_buildings, churu_other_buildings, churu_other_res], ignore_index=True)

# Verify count and save
print("Total merged buildings:", len(merged))

output = "churu_buildings_with_population.parquet"
merged.to_parquet(output, index=False, engine="pyarrow")

print(f"Saved all buildings to: {output}")

/usr/local/lib/python3.12/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Total merged buildings: 1481134
Saved all buildings to: churu_buildings_with_population.parquet